language: node_js
node_js:
    - 12.18.1
cache:
    directories:
        - node_modules
        - $HOME/.nvm
        - $HOME/.npm
git:
    depth: 3

script:
    - yarn
    - yarn build
    - mkdir output
    - cp package.json output/package.json
    - cp run.sh output/run.sh
    - cp -r .next output/.next

branches:
    only:
        - master
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    keep_history: true
    on:
        branch: master
