name: Serviços Minimos - OWID, RT, Cases Ilhas e ECDC
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
    schedule:
        - cron: '30 10,17 * * *'
#some comment
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 3
            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  npm ci
                  pip3 install -r requirements.txt
            - name: Cache
              uses: actions/cache@v2.1.6
              with:
                  path: 'node_modules'
                  key: 'node_modules'
            - name: Update OWID, Rt and Cases Ilhas
              run: |
                  git fetch
                  git config --global user.name "$user"
                  git config --global user.email "$email"
                  python3 ./automation/ecdc_parser.py
                  ./daemon.js --scrap owid

              env:
                  email: ${{secrets.EMAIL}}
                  user: ${{secrets.USER}}
