name: Serviços Minimos - Vacinas & Casos
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
    schedule:
        - cron: '10 16-22 * * *'
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 3
                  token: ${{ secrets.PAT}}

            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: yarn install --frozen-lockfile
            - name: Cache
              uses: actions/cache@v2.1.6
              with:
                  path: 'node_modules'
                  key: 'node_modules'
            - name: Update Vaccines
              run: |
                  curl -Ls $env --output .env
                  pip3 install firebase_admin python-dateutil
                  git fetch
                  git config --global user.name "$user"
                  git config --global user.email "$email"
                  HARDWARE=raspberry ./daemon.js --scrap vaccines

              env:
                  email: ${{secrets.EMAIL}}
                  user: ${{secrets.USER}}
                  env: ${{secrets.ENV_FILE}}
