name: Serviços Minimos - OWID, RT e Cases Ilhas
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
    schedule:
        - cron: '30 11,18 * * *'
#some comment
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: npm install
            - name: Cache
              uses: actions/cache@v2.1.6
              with:
                  path: 'node_modules'
                  key: 'node_modules'
            - name: Update OWID, Rt and Cases Ilhas
              run: |
                  echo $USER
                  git fetch
                  git config --global user.name "$user"
                  git config --global user.email "$email"
                  ./daemon.js --scrap owid

              env:
                  email: ${{secrets.EMAIL}}
                  user: ${{secrets.USER}}
